---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fresh-videoshop
  namespace: videoshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fresh-videoshop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fresh-videoshop
    spec:
      containers:
      - name: fresh-customer
        image: lastiverse/fresh-customer:0.0.1
        imagePullPolicy: Always
      - name: fresh-point
        image: lastiverse/fresh-point:0.0.1
        imagePullPolicy: Always
      - name: fresh-rent
        image: lastiverse/fresh-rent:0.0.1
        imagePullPolicy: Always
      - name: fresh-video
        image: lastiverse/fresh-video:0.0.1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fresh-videoshop
  namespace: videoshop
  labels:
    app: fresh-videoshop
spec:
  ports:
  - name: tcp-11001
    port: 11001
    targetPort: 11001
  - name: tcp-11002
    port: 11002
    targetPort: 11002
  - name: tcp-11003
    port: 11003
    targetPort: 11003
  - name: tcp-11004
    port: 11004
    targetPort: 11004
  selector:
    app: fresh-videoshop
  type: LoadBalancer
---
